on:
  push:
    branches: [main, master]

name: Extract data

jobs:
  Extract-Data:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
          use-public-rspm: true

      - name: Cache packages
      - uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      - name: Economic activity data
        run: |
          source("R/urls.R")
          source("R/utils.R")
          source("R/extract_data.R")
          rio::export(x = raw_icva, file = "dados.csv")
        shell: Rscript {0}

      - name: Commit & Push
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Teste
            commit_user_name: Fernando da Silva
            commit_user_email: fernando.schoulten@hotmail.com
            commit_author: Fernnado da Silva <fernando.schoulten@hotmail.com>
