on:
  push:
    branches: [main, master]

name: Extract data

jobs:
  Extract-data:
    runs-on: ubuntu-22.04

    env:
      OPENSSL_CONF: ./configs/network/openssl.cnf

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
          use-public-rspm: true

      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2

      - name: Economic activity data
        run: |
          source("R/parameters.R")
          source("R/utils.R")
          source("R/import.R")
          source("R/extract_data.R")
        shell: Rscript {0}

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Periodic data extraction
            commit_user_name: Fernando da Silva
            commit_user_email: fernando.schoulten@hotmail.com
            commit_author: Fernnado da Silva <fernando.schoulten@hotmail.com>
